apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: your-image-name:tag  # Replace with your actual image name and tag
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: student-app
